# Generated by Django 5.0.2 on 2024-04-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=50)),
                ('price', models.CharField(default=0, max_length=50)),
                ('name', models.CharField(default=0, max_length=50)),
                ('category', models.CharField(default=0, max_length=50)),
                ('description', models.CharField(default=0, max_length=200)),
                ('img_source', models.CharField(default=0, max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
