# Generated by Django 5.0.3 on 2024-04-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('state', models.CharField(default=0, max_length=100)),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
    ]
