# Generated by Django 5.0.2 on 2024-04-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('date', models.DateTimeField()),
                ('amountc', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
    ]
