# Generated by Django 5.0.2 on 2024-04-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amountc',
            field=models.IntegerField(),
        ),
    ]
