# Generated by Django 5.0.2 on 2024-04-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0005_alter_donation_amountc'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=0, max_length=50)),
                ('place', models.CharField(default=0, max_length=50)),
                ('purpose', models.CharField(default=0, max_length=100)),
                ('booking_date', models.DateField()),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField()),
                ('male', models.IntegerField(default=0)),
                ('female', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('total_guests', models.IntegerField(default=0)),
                ('total_rooms', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
