# Generated by Django 5.0.2 on 2024-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0006_room_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rooms', models.IntegerField(default=0)),
                ('availabel_rooms', models.IntegerField(default=0)),
            ],
        ),
    ]
