# Generated by Django 5.0.2 on 2024-04-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0007_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='availabel_rooms',
            new_name='available_rooms',
        ),
    ]
