# Generated by Django 5.0.2 on 2024-04-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0008_rename_availabel_rooms_rooms_available_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('date', models.DateTimeField()),
                ('items', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
