# Generated by Django 5.0.2 on 2024-04-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_admin', '0010_order_address_order_pincode_order_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
